FROM liuchong/rustup:stable


RUN apt-get update -qq && \
    apt-get install -y libpq-dev  && \
    rm -rf /var/lib/apt/lists/*

RUN cargo install diesel_cli --no-default-features --features postgres

RUN USER=root cargo new --bin rust-microservices


WORKDIR /rust-microservices
COPY ./Cargo.toml ./Cargo.toml
COPY ./init.sh ./init.sh
COPY ./migrations ./migrations
COPY ./src ./src


CMD ./init.sh

